// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EuropeJson from "./europe.json";

var europeMap = EuropeJson;

var ComposableMap = {};

var ZoomableGroup = {};

var Geographies = {};

var Geography = {};

var Marker = {};

export {
  europeMap ,
  ComposableMap ,
  ZoomableGroup ,
  Geographies ,
  Geography ,
  Marker ,
}
/* europeMap Not a pure module */
